In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sn

In [2]:
df = pd.read_csv('blake.csv')
df.head()

,clip_index,trick_index,trick,obstacle,obstacle_detailer,slowmo,bank,switch,line,video,year
0,1,1,ollie,gap,NaN,1,0,0,0,Programming Injection,2019
1,2,2,sw bs kickflip,gap,bump to gap,1,1,1,0,Programming Injection,2019
2,3,2,sw bs kickflip,gap,bump to gap,1,1,1,0,Programming Injection,2019
3,4,3,fs heelflip,flat,NaN,0,0,0,1,Programming Injection,2019
4,4,4,fakie fs noseslide to bigspin,ledge,NaN,0,0,0,1,Programming Injection,2019

In [3]:
df.trick.value_counts()[1:10]

ollie                                        11
fs heelflip                                  10
sw bs kickflip                               10
sw heelflip                                   9
bs crook                                      7
kickflip                                      7
sw kickflip to sw bs tailslide to regular     7
sw tre flip                                   6
kickflip to bs crook                          5
Name: trick, dtype: int64

In [4]:
df.obstacle.value_counts()

handrail     96
gap          70
rail         25
ledge        24
stairs       22
flat         20
hubba        17
wall          5
up            2
manny pad     2
pole          1
rock          1
hip           1
Name: obstacle, dtype: int64

In [5]:
df['obstacle_detailer'].value_counts()[1:15]

KeyError: 'obstacle-detailer'

In [6]:
df.groupby(['year', 'trick']).count()

                                               clip_index  trick_index  \
year trick
2011 bs crook                                           3            3
     bs feeble                                          1            1
     bs feeble to fs 180                                1            1
     bs feeble to fs 181                                1            1
     bs noseblunt                                       1            1
...                                                   ...          ...
2019 sw ollie                                           1            1
     sw tre flip                                        2            2
     sw tre flip to sw fs lipslide to regular           1            1
     tre flip                                           1            1
     wallie                                             1            1

                                               obstacle  obstacle_detailer  \
year trick
2011 bs crook                                         3                  3
     bs feeble                                        1                  1
     bs feeble to fs 180                              1                  1
     bs feeble to fs 181                              1                  1
     bs noseblunt                                     1                  1
...                                                 ...                ...
2019 sw ollie                                         1                  0
     sw tre flip                                      2                  2
     sw tre flip to sw fs lipslide to regular         1                  1
     tre flip                                         1                  0
     wallie                                           1                  0

                                               slowmo  bank  switch  line  \
year trick
2011 bs crook                                       3     3       3     3
     bs feeble                                      1     1       1     1
     bs feeble to fs 180                            1     1       1     1
     bs feeble to fs 181                            1     1       1     1
     bs noseblunt                                   1     1       1     1
...                                               ...   ...     ...   ...
2019 sw ollie                                       1     1       1     1
     sw tre flip                                    2     2       2     2
     sw tre flip to sw fs lipslide to regular       1     1       1     1
     tre flip                                       1     1       1     1
     wallie                                         1     1       1     1

                                               video
year trick
2011 bs crook                                      3
     bs feeble                                     1
     bs feeble to fs 180                           1
     bs feeble to fs 181                           1
     bs noseblunt                                  1
...                                              ...
2019 sw ollie                                      1
     sw tre flip                                   2
     sw tre flip to sw fs lipslide to regular      1
     tre flip                                      1
     wallie                                        1

[220 rows x 9 columns]

In [7]:
df['year'] = df.year.astype(str)

In [8]:
df.groupby('year').max()

AssertionError:

In [9]:
aggregated = df.groupby('year')

In [10]:
df2 = df
# total num tricks
aggregated = df2.groupby('year').max()['trick_index']
aggregated.name = 'total_num_tricks'
df3 = df2.join(aggregated, on='year')

# total num clips
aggregated = df2.groupby('year').max()['clip_index']
aggregated.name = 'total_num_clips'
df3 = df3.join(aggregated, on='year')

# total slowmo tricks
aggregated = df2.groupby('year').sum()['slowmo']
aggregated.name = 'total_slowmo_tricks'
df3 = df3.join(aggregated, on='year')

# total switch tricks
aggregated = df2.groupby('year').sum()['switch']
aggregated.name = 'total_switch_tricks'
df3 = df3.join(aggregated, on='year')

# total distinct
aggregated = df2.groupby('year').nunique()['trick']
aggregated.name = 'total_distinct_tricks'
df3 = df3.join(aggregated, on='year')

vids = df3.groupby('year')

# percent stair
obstacles = vids['obstacle'].agg(lambda x: (len(x[x=='stair']) + len(x[x=='gap']) ))
obstacles.name = 'stairs'
df3 = df3.join(obstacles, on="year")

# percent ledge
obstacles = vids['obstacle'].agg(lambda x: (len(x[x=='ledge'])))
obstacles.name = 'ledge'
df3 = df3.join(obstacles, on="year")

# percent transition
obstacles = vids['obstacle'].agg(lambda x: (len(x[x=='transition'])))
obstacles.name = 'transition'
df3 = df3.join(obstacles, on="year")

# percent handrail
obstacles = vids['obstacle_detailed'].agg(lambda x: (len(x[x=='handrail'])))
obstacles.name = 'handrail'
df3 = df3.join(obstacles, on="year")

cols_to_keep = ['year', 'total_num_tricks', 'total_num_clips', 'total_slowmo_tricks', 'total_switch_tricks',
       'total_distinct_tricks',
       'stairs', 'ledge', 'transition',
       'handrail']

df4 = df3[cols_to_keep].drop_duplicates().reset_index().drop(columns='index')

df5 = df4.drop(columns=['total_num_tricks', 'total_num_clips', 'total_slowmo_tricks', 'total_switch_tricks', 'total_distinct_tricks'])

perc_df = pd.melt(df5, id_vars =['year'], value_vars =['stairs', 'ledge', 'handrail', 'transition'])
perc_df.sort_values('year', inplace=True)
perc_df.columns = ['year', 'obstacle', 'count']

AssertionError: